<script src="{{ asset('public/assets/js/jquery-2.1.4.min.js') }}"></script>
<script src="{{ asset('public/assets/js/bootstrap.min.js') }}" ></script>
<script src="{{ asset('public/assets/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('public/assets/js/owl.thumbs.min.js') }}"></script>
<script src="{{ asset('public/assets/js/magnific-popup.min.js') }}"></script>
<script src="{{ asset('public/assets/js/ovic-mobile-menu.js') }}"></script>
<script src="{{ asset('public/assets/js/mobilemenu.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery.plugin-countdown.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery-countdown.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery.scrollbar.min.js') }}"></script>
<script src="{{ asset('public/assets/js/chosen.min.js') }}"></script>
<script src="{{ asset('public/assets/js/frontend.js') }}"></script>
<script src="{{ asset('public/assets/js/custom.js') }}"></script>